### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_FXOS8700#2]
In Adafruit_FXOS8700.cpp, in the function read8() is a while-loop after the Wire.requestFrom() to wait for data. That line can be removed, since there is no such thing to wait for incoming data. The Wire.requestFrom() waits until the I2C transaction has completely finished. When the Wire.requestFrom() returns, the received data is in a buffer in the Wire library.

**Comment by microbuilder** [comment]
Fixed
