### ISSUE TITLE
8G measurement range

### ISSUE THREAD

**Issue by ziatajo** [adafruit/Adafruit_FXOS8700#3]
Hi,
I'm trying to read the accelerometer with 8G range. For 2G and 4G it works fine. However, there is a problem with 8G. When I plot the data, I cannot reach +-8g the Raw values stop at around 6000 (when 8192 would be the max and 8g i think)
I had a look at the datasheet. It says, that if 8g is chosen, the HighResolution mode wont work. I don't know where in the library to see or change if this mode is active. Could that be the problem?
Can you help me there? i would need 8G as for my project 4G is not enough.

Also at the moment I can only measure with 100Hz, could I make this faster? How?

Thank you and best regards.

**Comment by caternuson** [comment]
It's probably the default enabling of low noise, the `lnoise` bit in the `CTRL_REG1` register being done in the `begin()` function here:
https://github.com/adafruit/Adafruit_FXOS8700/blob/be78a80f59256f8f75cad4f7b7a406e4c0b84465/Adafruit_FXOS8700.cpp#L184-L185
which apparently cannot be used with 8g mode:

![image](https://user-images.githubusercontent.com/8755041/123014290-c59fff00-d37a-11eb-8829-402d2b46dff7.png)

For the sample rate, it appears it is set to 100Hz in the same line of code above and there is currently no way to change that.
