### ISSUE TITLE
How is the Accelerometer range set

### ISSUE THREAD

**Issue by calisto27** [adafruit/Adafruit_FXOS8700#9]
It is advertised on adafruits website (and on the board itself) that the accelerometers range can be set to 2g, 4g and 8g.
however, neither the example sketch nor the tutorial demonstrate how.

I previously posted this on adafruits forum and was told that there is an internal range perimiter, but that nothing actually sets it, and that I should open an issue here.

Regards, Calisto Hüttich

**Comment by caternuson** [comment]
Please try the 2.1.0 release of the library when it becomes available:
https://github.com/adafruit/Adafruit_FXOS8700/releases/tag/2.1.0

It adds a new setter function for setting accelo range. There's a new line (commented out) in the example code that shows how to use:
```cpp
  // accelmag.setAccelRange(ACCEL_RANGE_8G);
```
Uncomment that to try it out. Possible settings are:
```
ACCEL_RANGE_2G
ACCEL_RANGE_4G
ACCEL_RANGE_8G
```

**Comment by calisto27** [comment]
Thanks so much for the quick response.
edit: thanks even more for actually editing the software, it works great!
